//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYMFIND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asociado
    {
        public int AsociadoID { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public int EstablecimientoID { get; set; }
        public string Rol { get; set; }
        public string Foto { get; set; }
    
        public virtual Establecimiento Establecimiento { get; set; }
    }
}
